# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install sphinx; fi

# command to run tests, e.g. python setup.py test
script:
    - python setup.py test
    - if [[ $TRAVIS_PYTHON_VERSION == 'docs' ]]; then  sphinx-build -b html docs _build/; fi
